// apps/webui/src/components/studio/TerminalPanel.tsx
import { useEffect, useRef, useState } from "react";
import { Terminal } from "xterm";
import { FitAddon } from "@xterm/addon-fit";
import "xterm/css/xterm.css";
import { trpc } from "@/lib/trpc";

export function TerminalPanel() {
  const termElRef = useRef<HTMLDivElement>(null);
  const [statusMsg, setStatusMsg] = useState("");
  const sessionIdRef = useRef<string | null>(null);
  const unsubRef = useRef<(() => void) | null>(null);

  useEffect(() => {
    const termEl = termElRef.current;
    if (!termEl) return;

    const term = new Terminal({
      cursorBlink: true,
      fontSize: 13,
      lineHeight: 1.2,
      fontFamily: 'ui-monospace, "Cascadia Code", Menlo, monospace',
      convertEol: true,
      scrollback: 5000,
      theme: {
        background: "#1e1e1e",
        foreground: "#d4d4d4",
        cursor: "#d4d4d4",
      },
    });
    const fitAddon = new FitAddon();
    term.loadAddon(fitAddon);
    term.open(termEl);

    const fitTerminal = () => {
      try {
        fitAddon.fit();
        const sid = sessionIdRef.current;
        if (sid) {
          void trpc.studio.terminal.resize.mutate({
            sessionId: sid,
            cols: term.cols,
            rows: term.rows,
          });
        }
      } catch {
        /* 容器尺寸为 0 时忽略 */
      }
    };

    const sendInput = (data: string) => {
      const sid = sessionIdRef.current;
      if (sid) {
        void trpc.studio.terminal.write.mutate({ sessionId: sid, data });
      }
    };

    const connect = () => {
      unsubRef.current?.();
      unsubRef.current = null;
      sessionIdRef.current = null;
      setStatusMsg("");

      const sub = trpc.studio.terminal.stream.subscribe(undefined, {
        onData: (msg) => {
          if (msg.type === "ready") {
            sessionIdRef.current = msg.sessionId;
            requestAnimationFrame(fitTerminal);
          } else if (msg.type === "output") {
            term.write(msg.data);
          } else if (msg.type === "error") {
            setStatusMsg(msg.message);
          } else if (msg.type === "exit") {
            setStatusMsg(`进程退出 (${msg.code})`);
          }
        },
        onError: () => setStatusMsg("WebSocket 连接失败"),
        onComplete: () => {
          setStatusMsg((prev) => prev || "连接已断开");
        },
      });
      unsubRef.current = () => sub.unsubscribe();
    };

    term.onData(sendInput);

    const ro = new ResizeObserver(() => {
      requestAnimationFrame(fitTerminal);
    });
    ro.observe(termEl);

    requestAnimationFrame(fitTerminal);
    connect();

    const reconnect = () => {
      term.clear();
      connect();
    };

    (termEl as HTMLDivElement & { __reconnect?: () => void }).__reconnect = reconnect;

    return () => {
      ro.disconnect();
      unsubRef.current?.();
      const sid = sessionIdRef.current;
      if (sid) {
        void trpc.studio.terminal.close.mutate({ sessionId: sid });
      }
      term.dispose();
    };
  }, []);

  const reconnect = () => {
    const el = termElRef.current as (HTMLDivElement & { __reconnect?: () => void }) | null;
    el?.__reconnect?.();
  };

  return (
    <div className="h-full flex flex-col min-h-0 border-t border-base-300 bg-[#1e1e1e] overflow-hidden">
      <div className="flex items-center justify-between px-2 py-1 border-b border-base-300 shrink-0 bg-base-200/30">
        <span className="text-xs font-medium text-base-content/70">终端</span>
        <button type="button" className="btn btn-ghost btn-xs" onClick={reconnect}>
          重连
        </button>
      </div>
      <div ref={termElRef} className="flex-1 min-h-0 overflow-hidden [&_.xterm]:h-full [&_.xterm]:p-1" />
      {statusMsg ? (
        <div className="px-2 py-1 text-xs text-error shrink-0 bg-base-200/30">{statusMsg}</div>
      ) : null}
    </div>
  );
}

// apps/webui/src/views/studio/pair/TerminalPanel.vue
<template>
  <div class="h-full flex flex-col min-h-0 border-t border-base-300 bg-[#1e1e1e] overflow-hidden">
    <div class="flex items-center justify-between px-2 py-1 border-b border-base-300 shrink-0 bg-base-200/30">
      <span class="text-xs font-medium text-base-content/70">终端</span>
      <button type="button" class="btn btn-ghost btn-xs" @click="reconnect">重连</button>
    </div>
    <div ref="termEl" class="flex-1 min-h-0 overflow-hidden" />
    <div v-if="statusMsg" class="px-2 py-1 text-xs text-error shrink-0 bg-base-200/30">{{ statusMsg }}</div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from 'vue'
import { Terminal } from 'xterm'
import { FitAddon } from '@xterm/addon-fit'
import 'xterm/css/xterm.css'
import { studioTerminalWsUrl } from '../../../api/client'

const termEl = ref(null)
const statusMsg = ref('')

let term = null
let fitAddon = null
let ws = null
let ro = null

function fitTerminal() {
  if (!fitAddon || !termEl.value) return
  try {
    fitAddon.fit()
    sendResize()
  } catch {
    /* 容器尺寸为 0 时忽略 */
  }
}

function sendInput(data) {
  if (ws?.readyState === WebSocket.OPEN) {
    ws.send(JSON.stringify({ type: 'input', data }))
  }
}

function sendResize() {
  if (!term || ws?.readyState !== WebSocket.OPEN) return
  ws.send(JSON.stringify({ type: 'resize', cols: term.cols, rows: term.rows }))
}

function connect() {
  disconnect(false)
  statusMsg.value = ''
  if (!term) return

  ws = new WebSocket(studioTerminalWsUrl())

  ws.onopen = () => {
    statusMsg.value = ''
    nextTick(() => {
      fitTerminal()
    })
  }

  ws.onmessage = (evt) => {
    try {
      const msg = JSON.parse(evt.data)
      if (msg.type === 'output') {
        term.write(msg.data)
      } else if (msg.type === 'ready') {
        nextTick(fitTerminal)
      } else if (msg.type === 'error') {
        statusMsg.value = msg.message
      } else if (msg.type === 'exit') {
        statusMsg.value = `进程退出 (${msg.code})`
      }
    } catch {
      term.write(evt.data)
    }
  }

  ws.onerror = () => {
    statusMsg.value = 'WebSocket 连接失败'
  }

  ws.onclose = () => {
    if (!statusMsg.value) statusMsg.value = '连接已断开'
  }
}

function disconnect(clearTerm = true) {
  ws?.close()
  ws = null
  if (clearTerm && term) term.clear()
}

function reconnect() {
  disconnect()
  connect()
}

onMounted(async () => {
  term = new Terminal({
    cursorBlink: true,
    fontSize: 13,
    lineHeight: 1.2,
    fontFamily: 'ui-monospace, "Cascadia Code", Menlo, monospace',
    convertEol: true,
    scrollback: 5000,
    theme: {
      background: '#1e1e1e',
      foreground: '#d4d4d4',
      cursor: '#d4d4d4',
    },
  })
  fitAddon = new FitAddon()
  term.loadAddon(fitAddon)
  term.open(termEl.value)

  term.onData(sendInput)

  ro = new ResizeObserver(() => {
    requestAnimationFrame(fitTerminal)
  })
  ro.observe(termEl.value)

  await nextTick()
  requestAnimationFrame(fitTerminal)
  connect()
})

onUnmounted(() => {
  ro?.disconnect()
  disconnect()
  term?.dispose()
})
</script>

<style scoped>
:deep(.xterm) {
  height: 100%;
  padding: 4px;
}
:deep(.xterm-viewport) {
  overflow-y: auto !important;
}
</style>
